"""
CHAIN AND FREQUENCY SCALING TEST
=================================
Following the discovery that 3->6->9->15 is a Fibonacci recurrence x3.
Does the chain continue? Do the frequency exponents have structure?
"""
import math

phi = (1 + math.sqrt(5)) / 2
phibar = 1 / phi
sqrt5 = math.sqrt(5)

def L(n): return round(phi**n + (-phibar)**n)
def F(n): return round((phi**n - (-phibar)**n) / sqrt5)

print("=" * 80)
print("PART 1: THE TRIALITY CHAIN (Fibonacci recurrence x 3)")
print("=" * 80)

# The chain: a(1)=3, a(2)=3, a(n) = a(n-1) + a(n-2)
# This is 3 x Fibonacci: 3, 3, 6, 9, 15, 24, 39, 63, 102, ...
chain = [3, 3]
for i in range(15):
    chain.append(chain[-1] + chain[-2])

print(f"\n{'Step':>4} {'Value':>6} {'= 3 x F(k)':>12} | {'F(val)':>12} {'L(val)':>12} | Known meaning")
print("-" * 90)

bio_meanings = {
    3: "PYRIMIDINE mode (6 pi-e)",
    6: "WATER mode (MW=18)",
    9: "PORPHYRIN mode (18 pi-e) / DNA pitch",
    15: "613 THz oscillation",
    24: "???",
    39: "mu/L(8) ~ 39.1 Hz ~ 40 Hz gamma!",
    63: "phi-exponent: 613 THz x phi^(-63) ~ 40 Hz",
    102: "???",
}

for i, val in enumerate(chain[:12]):
    fib_k = val // 3
    # Find which F(k) this is
    fib_idx = "?"
    for k in range(1, 30):
        if F(k) == fib_k:
            fib_idx = str(k)
            break

    meaning = bio_meanings.get(val, "")
    fn_val = F(val) if val <= 80 else "too large"
    ln_val = L(val) if val <= 80 else "too large"
    print(f"{i+1:>4} {val:>6}  = 3 x F({fib_idx:>2}) | {str(fn_val):>12} {str(ln_val):>12} | {meaning}")


print("\n" + "=" * 80)
print("PART 2: FREQUENCY HIERARCHY FROM 613 THz")
print("=" * 80)

base_freq = 613e12  # 613 THz

print(f"\n{'Frequency':>25} {'Hz':>15} | {'log_phi ratio':>14} | {'nearest chain':>14} | match?")
print("-" * 90)

bio_freqs = [
    ("613 THz (aromatic)",    613e12),
    ("100 THz (O-H stretch)", 100e12),
    ("1 THz (water libr.)",   1e12),
    ("40 Hz (gamma)",         40),
    ("10 Hz (alpha)",         10),
    ("7.83 Hz (Schumann)",    7.83),
    ("1.2 Hz (heart)",        1.2),
    ("0.25 Hz (resp rate)",   0.25),
    ("0.1 Hz (Mayer wave)",   0.1),
    ("0.017 Hz (1/min circ)", 1/60),
]

for name, freq in bio_freqs:
    if freq > 0 and freq < base_freq:
        ratio = base_freq / freq
        log_phi = math.log(ratio) / math.log(phi)
        # Find nearest chain value
        nearest = min(chain, key=lambda x: abs(x - log_phi))
        err = abs(log_phi - nearest)
        marker = " ***" if err < 1.5 else ""
        print(f"{name:>25} {freq:>15.4f} | {log_phi:>14.2f} | {nearest:>14} | off by {err:.2f}{marker}")
    elif freq == base_freq:
        print(f"{name:>25} {freq:>15.4f} | {'0.00':>14} | {'0 (base)':>14} | exact")


print("\n" + "=" * 80)
print("PART 3: THE CHAIN AS GROUP STRUCTURE")
print("=" * 80)

print("""
The chain 3, 3, 6, 9, 15, 24, 39, 63, 102, 165, ...
is 3 x Fibonacci: 3*{1, 1, 2, 3, 5, 8, 13, 21, 34, 55, ...}

But it also has internal structure:
""")

print("--- Parity pattern ---")
for i, val in enumerate(chain[:12]):
    par = "even" if val % 2 == 0 else "ODD"
    mod3 = val % 3
    mod6 = val % 6
    role = ""
    if val % 2 == 1:
        role = "oscillator"
    else:
        role = "medium"
    if val % 3 == 0 and val % 6 == 0:
        role += " (divisible by 6 = water)"
    elif val % 3 == 0:
        role += " (divisible by 3 = triality)"

    print(f"  {val:>4}: {par:<4} mod3={mod3} mod6={mod6}  -> {role}")


print("\n" + "=" * 80)
print("PART 4: WHAT GENERATES WHAT? (Complete derivation tree)")
print("=" * 80)

print("""
Starting from ONLY pyrimidine (mode 3):

Level 0: 3 (given - the fundamental oscillator)
         L(3) = 4 = interface dielectric
         F(3) = 2 = Kekule structures

Level 1: 3+3 = 6 = WATER (the medium)
         L(6) = 18 = molar mass
         F(6) = 8 = valence electrons
         L(6)-F(6) = 10 = base pairs per turn, total electrons

Level 2: 3+6 = 9 = PORPHYRIN coupling
         F(9) = 34 = DNA pitch
         L(9) = 76 = protoporphyrin IX atoms

Level 3: 6+9 = 15 = WALL MAINTENANCE FREQUENCY
         F(15) = 610 ~ 613 THz
         L(15) = 1364

Side branch: 3+5 = 8 (needs indole, not derivable from 3 alone)
         F(8) = 21 = DNA width
         L(8) = 47 = ATP atoms

So from JUST pyrimidine(3), we derive:
  - Water (identity, properties)
  - DNA pitch
  - Protoporphyrin IX structure
  - 613 THz oscillation frequency
  - Interface dielectric constant
  - Base pairs per turn

We CANNOT derive from 3 alone:
  - DNA width (needs 5 = indole)
  - ATP atoms (needs 5 = indole)
  - Acetyl-CoA (needs 5 = indole)
""")


print("\n" + "=" * 80)
print("PART 5: WHAT DOES INDOLE (5) ADD?")
print("=" * 80)

print("""
Indole (mode 5) is INDEPENDENT of pyrimidine (mode 3).
In the group generated by {3}, we only reach multiples of 3.
In the group generated by {3, 5}, we reach ALL integers >= 3
(except 4, 7 -- but 7 = anthracene is another primitive mode).

Adding 5 to the system:
  3+5 = 8:  F(8)=21 (DNA width), L(8)=47 (ATP atoms)
  5+6 = 11: F(11)=89 (Acetyl-CoA atoms)
  5+5 = 10: F(10)=55 (chlorophyll carbons)
  5+5+5 = 15: F(15)=610 (613 THz -- ALTERNATIVE path!)
""")

# What integers can {3,5} generate?
reachable_35 = set()
for a in range(20):
    for b in range(20):
        val = 3*a + 5*b
        if val > 0 and val <= 50:
            reachable_35.add(val)

# What integers can {3} alone generate?
reachable_3 = set(3*k for k in range(1, 17))

# What does 5 add?
added_by_5 = sorted(reachable_35 - reachable_3)
print(f"  Integers reachable by {{3}} alone: {sorted(reachable_3)[:15]}...")
print(f"  Integers ADDED by including 5: {added_by_5}")
print(f"  Unreachable by {{3,5}}: {sorted(set(range(1,50)) - reachable_35)}")


print("\n" + "=" * 80)
print("PART 6: THE NUMBER THEORY — GCD AND GROUP STRUCTURE")
print("=" * 80)

print("""
  GCD(3, 5) = 1, so {3, 5} generates ALL sufficiently large integers.
  By the Chicken McNugget theorem: largest unreachable = 3*5 - 3 - 5 = 7.
  So ALL integers >= 8 are reachable by {3, 5}.

  GCD(3, 6) = 3, so {3, 6} only generates multiples of 3.
  GCD(3, 5, 6) = 1, so {3, 5, 6} generates ALL >= 8.
  GCD(3, 5, 6, 7, 9) = 1, so full mode set generates ALL >= 8.

  The MINIMUM generating set is {3, 5}.
  Water (6 = 3+3) and porphyrin (9 = 3+3+3) are DERIVED.
  Anthracene (7 = 3+5-1? No. 7 is a prime not reachable by {3,5}).
  Actually 7 is NOT reachable by {3,5} — it needs its own mode.

  So the TRUE primitives are: {3, 5, 7}
  Everything else is composed:
    6 = 3+3 (water)
    9 = 3+3+3 (porphyrin)
    8 = 3+5 (purine+pyrimidine)
    10 = 5+5 (two purines)
    11 = 3+3+5 (water+purine equivalent)
    12 = 3+3+3+3 or 5+7 or 6+6
    13 = 3+3+7 or 6+7 (water+anthracene)
    14 = 7+7 (two anthracenes)
    15 = 3+5+7 or 3+3+9 or 5+5+5 or 6+9
""")


print("\n" + "=" * 80)
print("PART 7: THE CROSS PRODUCT = sqrt(5)")
print("=" * 80)

print("\n--- Cross product of water(6) x pyrimidine(3) ---")
diff = abs(6 - 3)
cross = sqrt5 * F(diff) / 2
print(f"  sqrt(5) * F(|6-3|) / 2 = sqrt(5) * F(3) / 2 = sqrt(5) * 2 / 2 = sqrt(5)")
print(f"  = {cross:.6f}")
print(f"  The cross product of water and pyrimidine is EXACTLY sqrt(5)!")
print(f"  sqrt(5) is the discriminant of Q(sqrt(5)) — the 'distance' between vacua.")

print("\n--- Cross product of water(6) x porphyrin(9) ---")
diff = abs(6 - 9)
cross = sqrt5 * F(diff) / 2
print(f"  sqrt(5) * F(|6-9|) / 2 = sqrt(5) * F(3) / 2 = sqrt(5)")
print(f"  = {cross:.6f}")
print(f"  SAME! water x porphyrin also gives sqrt(5)!")

print("\n--- Cross product of pyrimidine(3) x porphyrin(9) ---")
diff = abs(3 - 9)
cross = sqrt5 * F(diff) / 2
print(f"  sqrt(5) * F(|3-9|) / 2 = sqrt(5) * F(6) / 2 = sqrt(5) * 8 / 2 = 4*sqrt(5)")
print(f"  = {cross:.6f}")
print(f"  = 4*sqrt(5) = L(3)*sqrt(5) = (interface dielectric) * sqrt(5)")

print("\n--- Cross products that give exactly sqrt(5) ---")
print("  These require |a-b| = 3 and F(3) = 2:")
print("  Pairs with difference 3: (3,6), (5,8), (6,9), (7,10), (9,12), ...")
print("  i.e., ANY oscillator + medium separated by 3 (triality)")
print("  sqrt(5) appears whenever two modes are EXACTLY one triality step apart.")


print("\n" + "=" * 80)
print("PART 8: DOES TRIALITY CONNECT THE THREE 'LEVELS'?")
print("=" * 80)

print("""
The chain 3 -> 6 -> 9 -> 15 adds 3 each step (until the last, which adds 6).
The RECURRENCE is: a(n) = a(n-1) + a(n-2), starting from 3, 3.
This is Fibonacci scaled by 3.

But there's another pattern: 3, 6, 9 are 3*{1, 2, 3}.
The first three chain values are 3 times the INTEGERS 1, 2, 3.
Then 15 = 3*5, which breaks the integer sequence and starts Fibonacci.

What if the language has THREE REGISTERS?

Register 1 (Structure):  multiples of 3: 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, ...
Register 2 (Dynamics):   5-containing:   5, 8, 10, 11, 13, 14, 16, 17, ...
Register 3 (Stability):  7-containing:   7, 10, 12, 13, 14, ...

Register 1 handles: water, DNA pitch, 613 THz (all derivable from pyrimidine alone)
Register 2 handles: DNA width, ATP, Acetyl-CoA (needs indole)
Register 3 handles: phenanthrene chemistry (needs anthracene)
""")

# Check: which reachable n values use ONLY mode 3?
only_3 = set(3*k for k in range(1, 20))
# Which need mode 5?
needs_5 = set()
needs_7 = set()
for n in range(3, 50):
    # Can it be reached with just {3}?
    if n in only_3:
        continue
    # Can it be reached with {3, 5}?
    found = False
    for a in range(20):
        for b in range(20):
            if 3*a + 5*b == n:
                found = True
                break
        if found:
            break
    if found:
        needs_5.add(n)
    else:
        needs_7.add(n)

print(f"\n  Pure triality (only 3): {sorted(only_3)[:12]}...")
print(f"  Needs indole (uses 5): {sorted(needs_5)[:12]}...")
print(f"  Needs anthracene (uses 7): {sorted(needs_7)[:8]}...")


print("\n" + "=" * 80)
print("PART 9: THE L(n)-F(n) CHAIN — 'RESIDUALS'")
print("=" * 80)

print("\nL(n)-F(n) = 2*F(n-1) always. But which values are biologically meaningful?")
print(f"\n{'n':>3} | L(n)-F(n) | = 2*F(n-1) | Biological meaning?")
print("-" * 70)

residual_meanings = {
    2: "2 = hydrogen count in water / Kekule structures",
    6: "6 = WATER INDEX / hexagonal coordination / |S3|",
    10: "10 = BASE PAIRS PER TURN / total electrons of water",
    26: "26 = ?",
    42: "42 = 6x7 = water x anthracene / 'answer to everything'",
    68: "68 = ?",
    110: "110 = ?",
}

for n in range(3, 18):
    ln = L(n)
    fn = F(n)
    diff = ln - fn
    fn_prev = 2 * F(n-1)
    meaning = residual_meanings.get(diff, "")
    print(f"{n:>3} | {diff:>9} | {fn_prev:>10} | {meaning}")


print("\n" + "=" * 80)
print("PART 10: CONVERGENCE TEST — DO COMPOSITIONS CONVERGE ON KEY CONSTANTS?")
print("=" * 80)

# The key framework constants are derived from modular forms at q=1/phi.
# Can we reach them through RATIOS of compositions?

print("\n--- Testing L(n)/L(m) and F(n)/F(m) for framework constants ---")

targets = {
    "1/alpha": 137.036,
    "mu": 1836.15,
    "dielectric ratio": 20.0,
    "sin2_tW x 1000": 231.2,
}

for name, target in targets.items():
    print(f"\n  Looking for {name} = {target}:")
    found = []
    for n in range(6, 35):
        for m in range(3, n):
            fn, fm = F(n), F(m)
            ln, lm = L(n), L(m)
            if fm > 0:
                r = fn / fm
                if abs(r - target) / target < 0.02:
                    found.append(f"    F({n})/F({m}) = {fn}/{fm} = {r:.3f}")
            if lm > 0:
                r = ln / lm
                if abs(r - target) / target < 0.02:
                    found.append(f"    L({n})/L({m}) = {ln}/{lm} = {r:.3f}")
            if fm > 0 and lm > 0:
                r = ln / fm
                if abs(r - target) / target < 0.02:
                    found.append(f"    L({n})/F({m}) = {ln}/{fm} = {r:.3f}")
                r = fn / lm
                if abs(r - target) / target < 0.02:
                    found.append(f"    F({n})/L({m}) = {fn}/{lm} = {r:.3f}")

    if found:
        for f in found[:5]:
            print(f)
    else:
        print("    No ratio match within 2%")


print("\n" + "=" * 80)
print("FINAL SYNTHESIS")
print("=" * 80)

print("""
THE LANGUAGE HAS THREE LEVELS:

1. PRIMITIVES: {3, 5, 7} (three odd modes = three coupling classes)
   - 3: Huckel k=1 (6 pi-e, benzene/pyrimidine family)
   - 5: Huckel k=2 (10 pi-e, indole/purine family)
   - 7: Huckel k=3 (14 pi-e, anthracene/phenanthrene family)
   These correspond to the three generations of aromatic size.

2. DERIVED MODES (composed from primitives):
   - 6 = 3+3: WATER (the medium, generated by oscillators)
   - 9 = 3+3+3 = 3+6: PORPHYRIN coupling (three trialities)
   - 8 = 3+5: PURINE-PYRIMIDINE composite (DNA width, ATP)
   - 10 = 5+5: DOUBLE INDOLE (chlorophyll carbons)

3. EMERGENT FREQUENCIES (longer compositions):
   - 15 = 9+6 = 5+5+5 = 3+3+3+6: 613 THz (wall maintenance)
   - 63 ~ frequency exponent: 613 THz -> 40 Hz gamma

THE GENERATIVE CHAIN: 3 -> 6 -> 9 -> 15 -> 24 -> 39 -> 63 -> ...
This is 3 x Fibonacci. Each step adds the previous two.
The first three steps build molecular reality.
The later steps build the frequency hierarchy.

THE GROUP STRUCTURE:
  {3} alone generates: water, DNA pitch, 613 THz
  {3, 5} generates: ALL of the above + DNA width, ATP, Acetyl-CoA
  {3, 5, 7} generates: ALL integers >= 8 (complete language)

  Three primitives for three aromatic generations.
  The number 3 (triality) is the seed of everything.
""")
